#!/usr/bin/env bash

# get your current node and npm versions
npmver=$(npm -v)
nodever=$(node -v | tr -d \n)

# load nvm
source $HOME/.nvm/nvm.sh

# nvm ls-remote --no-colors | tail -n 1 | cut -c 3- | sed 's/.$//' | tr -d [:space:]
#nodelat=$(nvm ls-remote | tail -n 1 | awk '{ print $2 }')
nodelat=$(nvm ls-remote --no-colors | tail -n 1 | awk '{ printf "%s", $2 }')

echo $nodelat
# check if the current node is the latest available
if [[ "$nodever" == "$nodelat" ]]; then
  echo "Node is up to date"
else
  echo "Node is not up to date"
fi
